name: StatBadge
version: '${version}'
main: com.gmail.necnionch.myplugin.statbadge.bukkit.plugin.StatBadgePlugin
api-version: '1.13'
authors: [Necnion8]
website: https://github.com/Necnion8/StatBadge

softdepend:
  - MythicMobs
  - Lands
  - AFKPlus
  - PlaceholderAPI
  - KyoriAdventureLib

commands:
  badges:
    permission: statbadge.command.badges
  statbadge:
    permission: statbadge.command.statbadge

permissions:
  statbadge.command.badges:
    default: true
  statbadge.command.statbadge:
    default: op
